apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: penguincrm
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: migration
          image: ghcr.io/saigear99/penguincrm-api:latest  
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: api-secrets 
      restartPolicy: Never
  backoffLimit: 4